<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6VTJ9AE" name="Default test(failed)" tests="2" failures="1" timestamp="1 Jul 2019 18:44:27 GMT" time="0.027" errors="0">
  <testcase name="test2" time="0.006" classname="demo.TestNGRetryFailedDemo"/>
  <testcase name="test3" time="0.003" classname="demo.TestNGRetryFailedDemo">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:23)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test(failed) -->
